<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <!-- Audit Trails related related packages --> 
        <PackageReference Include="EntityFrameworkCore.CreatedUpdatedDate" Version="8.0.0"/> 
        <!-- Entity Framework Core related packages -->
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational.Design" Version="1.1.6"/>
        <!-- MySQL Entity Framework Core related packages --> 
        <PackageReference Include="MySql.EntityFrameworkCore" Version="9.0.6"/> 
        <!-- Naming convention conversion related packages --> 
        <PackageReference Include="Humanizer" Version="2.14.1"/> 
        <!-- Swagger related packages -->
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6"/>
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="9.0.6"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Reservations\Application\Internal\" />
      <Folder Include="Reservations\Domain\Model\" />
      <Folder Include="Reservations\Domain\Queries\" />
      <Folder Include="Reservations\Domain\Repositories\" />
      <Folder Include="Reservations\Domain\Services\" />
      <Folder Include="Rooms\Application\Internal\" />
      <Folder Include="Rooms\Domain\Commands\" />
      <Folder Include="Rooms\Domain\Model\" />
      <Folder Include="Rooms\Domain\Queries\" />
      <Folder Include="Rooms\Domain\Repositories\" />
      <Folder Include="Rooms\Domain\Services\" />
      <Folder Include="Rooms\Infrastructure\Repositories\" />
      <Folder Include="Rooms\Interfaces\REST\Resource\" />
      <Folder Include="Rooms\Interfaces\REST\Transform\" />
      <Folder Include="Shared\Domain\" />
      <Folder Include="Subscriptions\Application\Internal\" />
      <Folder Include="Subscriptions\Domain\Commands\" />
      <Folder Include="Subscriptions\Domain\Model\" />
      <Folder Include="Subscriptions\Domain\Queries\" />
      <Folder Include="Subscriptions\Domain\Repositories\" />
      <Folder Include="Subscriptions\Domain\Services\" />
      <Folder Include="Subscriptions\Infrastructure\Repositories\" />
      <Folder Include="Subscriptions\Interfaces\REST\Resource\" />
      <Folder Include="Subscriptions\Interfaces\REST\Transform\" />
      <Folder Include="users\Application\Internal\" />
      <Folder Include="users\Domain\Commands\" />
      <Folder Include="users\Domain\Model\" />
      <Folder Include="users\Domain\Queries\" />
      <Folder Include="users\Domain\Repositories\" />
      <Folder Include="users\Domain\Services\" />
      <Folder Include="users\Infrastructure\Repositories\" />
      <Folder Include="users\Interfaces\REST\Resource\" />
      <Folder Include="users\Interfaces\REST\Transform\" />
    </ItemGroup>

</Project>
